Error: HTML emails are shown with escaped tags
This is because SwiftMailer verifies that the body is an object of type Drupal\Component\Render\MarkupInterface, otherwise it escapes its value

(See method: Drupal\swiftmailer\Plugin\Mail\SwiftMailer::massageMessageBody)